// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9Eth33d5ml7IfmaM7hjmfCn-voD3aME',
    appId: '1:668719922722:android:ae460395664a2f4cda147b',
    messagingSenderId: '668719922722',
    projectId: 'journalapp-7465a',
    storageBucket: 'journalapp-7465a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWwv8LTbXbbMJvhAgVe5XRUVdx1RhJbI',
    appId: '1:668719922722:ios:f0cd35564e46980dda147b',
    messagingSenderId: '668719922722',
    projectId: 'journalapp-7465a',
    storageBucket: 'journalapp-7465a.appspot.com',
    iosClientId: '668719922722-crnc20heutlc8u4d53f4p2d7qb7aj2u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.journalApp',
  );
}
